name: Commit Message Check
on:
  push:
    branches: [ main ]
jobs:
  commit-message-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check commit messages
        run: |
          # 定义提交信息格式规则
          commit_pattern='^(fix|feat|docs|style|refactor|test|chore|perf|ci)(\([a-zA-Z0-9]{1,20}\))?: (.{1,80})$'
          
          # 获取所有提交信息并检查格式
          for commit in $(git log --format='%H' origin/main..HEAD); do
            message=$(git log -1 --format='%s' $commit)
            echo ">>> message: $message"
            if [[ ! $message =~ $commit_pattern ]]; then
              echo "错误: 提交信息不符合格式要求($message)"
              echo "正确格式: <类型>[(<范围>)]: <描述>"
              echo "字符限制: 范围-限制20字符  描述-限制80字符"
              exit 1
            fi
          done  
