name: 自动部署

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置环境变量
        id: set-env
        run: |
          echo "GIT_DEPLOY_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "部署环境：prod生产环境"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "部署环境：dev开发环境"
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "ENVIRONMENT=pre" >> $GITHUB_ENV
            echo "部署环境：pre预发环境"
          else
            echo "不支持此分支部署"
            exit 1
          fi
          echo "部署分支${{ github.ref }}"
          echo "git 版本号${{ github.sha }}"