name: Deploy deepiano-api to Server

on:
  push:
    branches:
      - main
      - dev
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 防止网络超时卡死

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Use variables
        run: |
          echo "remote_host variable : $remote_host"
          echo "remote_user variable : $remote_user"
          echo "remote_key variable : $remote_key"
          echo "vars.prod_deploy.SERVER_IP: ${{ vars.prod_deploy.SERVER_IP }}"
          echo "secrets.SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "secrets.prod_deploy.SSH_PRIVATE_KEY: ${{ secrets.prod_deploy.SSH_PRIVATE_KEY }}"

        env:
          remote_host: ${{ vars.SERVER_IP }}
          remote_user: ${{ vars.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 设置环境变量
        id: set-env
        run: |
          echo "GIT_DEPLOY_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT=prod
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            ENVIRONMENT=dev
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            ENVIRONMENT=pre
          else
            echo "不支持此分支部署"
            exit 1
          fi
          echo "部署分支: ${{ github.ref }}"
          echo "GIT版本号: ${{ github.sha }}"
          echo "部署环境: $ENVIRONMENT"
          
          PROJECT_NAME="deepiano-api-${ENVIRONMENT}"
          REMOTE_PROJECT_DIR="/srv/ops/deploy/projects/${PROJECT_NAME}"
          echo "部署项目: ${PROJECT_NAME}"
          echo "源码路径: ${REMOTE_PROJECT_DIR}"
          
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
          echo "REMOTE_PROJECT_DIR=${REMOTE_PROJECT_DIR}" >> $GITHUB_ENV

      - name: Init remote project directory
        uses: appleboy/ssh-action@master
        with:
          host: 47.93.86.147
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REMOTE_PROJECT_DIR
          script: |
            if [[ -d "${REMOTE_PROJECT_DIR}" ]]; then
              rm -rf "${REMOTE_PROJECT_DIR}";
            fi
            echo "目录: ${REMOTE_PROJECT_DIR}";
            mkdir -p "${REMOTE_PROJECT_DIR}";

      - name: Install rsync (for incremental transfer)
        run: sudo apt-get install -y rsync

      - name: Push code to server via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -arcvz --delete --exclude="*.pyc" --exclude='__pycache__'  --progress   # 增量同步并删除冗余文件
          path: ./                 # 同步当前目录所有文件
          remote_path: ${REMOTE_PROJECT_DIR}
          remote_host: 47.93.86.147
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: 47.93.86.147
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /srv/ops/bin/ops_deploy.sh      # 执行本地部署脚本
            echo "Deployment completed!"

      - name: Run Ansible Playbook
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_NAME,REMOTE_PROJECT_DIR,GIT_DEPLOY_VERSION
          script: |
            cd /home/ubuntu/workplace/ops/apps
            ansible-playbook deepiano-api.yml -i hosts.d/deepiano-api-hosts.yaml  -l $PROJECT_NAME -e "REMOTE_PROJECT_DIR=$REMOTE_PROJECT_DIR deploy_version=$GIT_DEPLOY_VERSION"
