name: 自动部署

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置环境变量
        id: set-env
        run: |
          echo github.ref="${{ github.ref }}"
          echo github.sha="${{ github.sha }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "部署目标环境：生产环境"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "部署目标环境：预发布环境"
          elif [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
            echo "部署目标环境：开发环境"
          else
            echo "不支持在此分支部署"
            exit 1
          fi